### ISSUE TITLE
Corrupt source files?

### ISSUE THREAD

**Issue by Balooga** [jkotlinski/durexforth#180] opened 2016-01-22 06:17 UTC
The following has happened to me on a few occasions where upon returning to DurexForth, vi reports previously successfully saved source files as empty.  Usually there is a corresponding "." prefixed file which does contain the source - however attempting to compile the "." version always returns "err". 

Any thoughts on possible causes?

Thanks

**Comment by jkotlinski** [comment] 2016-01-22 06:22
Hi Balooga, what is your setup? Real hardware? Emulator (true drive emulation or not)?

**Comment by jkotlinski** [comment] 2016-01-22 06:27
Also... how do you usually save?
I noticed there is a bug now with :w!<filename>... if using backspace, the backspace gets stored as part of the filename

**Comment by Balooga** [comment] 2016-01-22 06:31
I'm running x64sc VICE.  Yes, True Drive Emulation is enabled.  I typically open files from the REPL using;

  s" a-file" vi

**Comment by jkotlinski** [comment] 2016-01-22 06:35
How do you save typically? ZZ or :w ?

**Comment by Balooga** [comment] 2016-01-22 06:36
Always ":w", with no filename specified,

**Comment by jkotlinski** [comment] 2016-01-22 06:56
Which version are you using? I made a change for v1.5.1 which could have broken things...

**Comment by Balooga** [comment] 2016-01-22 06:57
Looks like version 1.5.1

**Comment by jkotlinski** [comment] 2016-01-22 22:07
Another question... which diskdrive version are you emulating? 1541? 1541-II?

**Comment by Balooga** [comment] 2016-01-22 22:20
I'm using a Jiffydos kernel, on 1541-II.

**Comment by jkotlinski** [comment] 2016-01-22 23:24
OK, I found one insanely bad issue now where files could not be save if the filename was longer than 5 characters. Could that be it?

**Comment by Balooga** [comment] 2016-01-23 00:06
Yup, that might be the root cause.  My filenames are all longer than 5
characters.

**Comment by jkotlinski** [comment] 2016-01-23 00:45
OK, in that case the problem might be fixed by now. Sorry for the inconvenience!

**Comment by Balooga** [comment] 2016-01-23 01:09
But it is intermittent. Saves/loads ok, and then suddenly the file is
empty.

**Comment by jkotlinski** [comment] 2016-01-23 09:28
Maybe needs further investigation then. Do you maybe have a .d64 with such an empty file? I don't know but maybe it could give hints why it happened.

**Comment by jkotlinski** [comment] 2016-01-23 09:31
OK, will investigate a bit further.

**Comment by jkotlinski** [comment] 2016-01-23 10:24
I am not sure I fixed everything, but anyway I added a preliminary v1.5.4 release now.
One of the things that changed is that any drive error message from saving in vi will be displayed properly, and has to be dismissed by pressing a key. So it would probably give good information if you use this version, look out for suspicious drive error messages, and if the problems happen still it would be interesting to see what the .d64 looks like.

**Comment by Balooga** [comment] 2016-01-23 18:22
Could the issue have been caused by the save-and-replace bug which was recently fixed?
  
> * bugfix: avoided 1541 save-with-replace bug for vi save

I've been using v1.5.3 now and there has not been a recurrence.

**Comment by jkotlinski** [comment] 2016-01-23 18:53
Don't think so, it should not affect JiffyDOS.

**Comment by Balooga** [comment] 2016-01-23 21:56
I'm going to close as latest version seems to have fixed the issue.

**Comment by Balooga** [comment] 2016-01-23 23:27
Just had this issue again on v1.5.3, so re-opening.  The file with the issue is "display".

> vi display

[forth-1.d64.zip](https://github.com/jkotlinski/durexforth/files/102082/forth-1.d64.zip)

**Comment by jkotlinski** [comment] 2016-01-24 00:30
Hi, could you try with v1.5.4? That's where the potential fixes are.

https://github.com/jkotlinski/durexforth/releases/tag/v1.5.4

**Comment by Balooga** [comment] 2016-01-24 00:33
Will do.

**Comment by Balooga** [comment] 2016-01-24 06:06
What is the difference between a`*PRG` and `PRG` file - see the attachment.  The `*PRG` file is not readable by vi.

![forth-ls](https://cloud.githubusercontent.com/assets/167243/12534775/65d38f44-c21c-11e5-8b17-2f49834b56a1.jpg)

**Comment by jkotlinski** [comment] 2016-01-24 07:41
The *PRG means that the file did not finish saving and, as a result, it is not readable. This typically happens if one turns off the C64 when the drive lamp is still lit.

**Comment by jkotlinski** [comment] 2016-01-27 19:34
Hi @Balooga , when you get to try out v1.5.4, let me know and I will put it out as "official" release :)

**Comment by Balooga** [comment] 2016-01-27 21:32
I have been using 1.5.4 for several days now, and the corrupt file
bug seems to be fixed. I would suggest making this an official release.
Thanks for the help.

**Comment by jkotlinski** [comment] 2016-01-27 22:05
Great! Thanks!

**Closed by jkotlinski** 2016-01-27 22:05 UTC
Labels: bug, Priority-High

**Comment by Balooga** [comment] 2016-02-26 05:18
I think I may have identified the cause.  When VICE crashes with VI running, the file being edited may become corrupt.

**Comment by jkotlinski** [comment] 2016-02-27 09:29
@Balooga To summarize then, I guess this is not a bug in Durexforth?

**Comment by Balooga** [comment] 2016-03-05 18:40
Yes, no bug in Durexforth. Thanks for the help though.
